name: global_strongman
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_platform_widgets: ^1.9.5
  sign_button: ^2.0.1
  introduction_screen: ^2.1.0
  flutter_svg: ^0.22.0
  sprung: ^3.0.0
  multi_select_flutter: ^4.0.0
  image_picker: ^0.8.4+3
  flutter_form_builder: ^6.2.0
  firebase_core: ^1.8.0
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.1.4
  firebase_storage: ^10.0.6
  page_transition: "^2.0.4"
  google_sign_in: ^5.0.3
  flutter_facebook_auth: "^3.5.3"
  sign_in_with_apple: ^3.2.0
  crypto: ^3.0.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  charts_flutter: ^0.12.0
  video_player: ^2.2.7
  flutter_rating_bar: ^4.0.0
  chewie: ^1.2.2
  sliding_sheet: ^0.5.2
  flutterfire_ui: ^0.2.0+2
  shared_preferences: ^2.0.11
  table_calendar: ^3.0.3
  intl: ^0.17.0
  provider: ^6.0.2
  onboarding: ^2.1.0
  timeline_tile: ^2.0.0
  focused_menu: ^1.0.5
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  timeago: ^3.1.0

dependency_overrides:
  provider: ^6.0.0 # for chewie 1.2.2
  # platform: ^3.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/global_strongman_logo_AppStore.jpeg"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
